### ISSUE TITLE
[QUESTION] Can sqlite be used for multi-node multi-GPU runs?

### ISSUE THREAD

**Issue by Nanthini10** [jrbourbeau/dask-optuna#17]
For the storage, what would be the recommended way to run a multi-node experiment?

**Comment by mrocklin** [comment]
Hi @Nanthini10 !  

Yes, you can use any Optuna storage within a DaskStorage and it will be multi-node safe.  This includes sqlite or in-process.

The example in the README would work fine in a multi-node environment if you switched out the local Client for a Client pointing to a remote system.

**Comment by mrocklin** [comment]
Or, more generally, there are no special considerations that you need to take with dask-optuna when running on multiple nodes, other than the normal considerations  you would take like making sure that you have the same software environments everywhere.  The dask-optuna code itself is agnostic to being run on one node or on many.

**Comment by Nanthini10** [comment]
Thanks for the clarification, @mrocklin.
